### PR TITLE
Issue #368: Handle symlinked coverage target

### PR DESCRIPTION
**Pull request by rpoyner-tri**
Closes: #368

### CODE REVIEW

**Comment by rpoyner-tri** [comment]
@SimonKagstrom : feel free to use and/or improve on this patch. The test covers the situation described in #368, but could probably be improved. I was able to work out how to run the tests locally, and verified passing-with-fix, and failing-without fix.

**Comment by SimonKagstrom** [comment]
Merged! Thanks for taking the time to write the regression test as well!

**Comment by rpoyner-tri** [comment]
Glad to be of service. Been using kcov for many years; thanks for your work on it!

**Comment by SimonKagstrom** [comment]
Happy to hear that, thanks a lot!

**Pull request merged**
