### PR TITLE
ci: Add riscv

### PR DESCRIPTION
**Pull request by SimonKagstrom**

### CODE REVIEW

**Comment by SimonKagstrom** [comment]
@williamdes your work for dockerhub made me remember this branch I had laying around. It had a lot of other changes to run tests as well, but those doesn't work anyway. So now it's just adding riscv to the github ci.

**Review by williamdes — APPROVED** [review]
Typo on the commit message
Also, it's not possible to enable riscv64 for bookworm images because the Docker hub image is not build for riscv64 itself. But alpine does have it.

**Comment by SimonKagstrom** [comment]
Sorry, merged before I had read the comment :-/

I guess it has to be known as a 62 bit CPU in kcov!


Anyway, this is not for the docker builds, so only to verify that it's possible to build in general.

**Comment by williamdes** [comment]
> Sorry, merged before I had read the comment :-/
> 
> I guess it has to be known as a 62 bit CPU in kcov!
> 
> Anyway, this is not for the docker builds, so only to verify that it's possible to build in general.

Yup, that's all good
Nice we have a check for it

**Comment by williamdes** [comment]
Can you add a musl VM?

**Comment by SimonKagstrom** [comment]
> Can you add a musl VM? (Alpine)

Not quite sure how to do that? You mean for the github actions as a build job? With some googling, this turned up, https://github.com/jirutka/setup-alpine, maybe something like that?

**Comment by williamdes** [comment]
> > Can you add a musl VM? (Alpine)
> 
> Not quite sure how to do that? You mean for the github actions as a build job? With some googling, this turned up, https://github.com/jirutka/setup-alpine, maybe something like that?

It definitely looks like the way to do this !

Another way is to set the image in a pure Docker way
```yaml
    job-name:
        container:
            image: alpine:3.20
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
```

**Pull request merged**
