### PR TITLE
Minor "unused" fixes

### PR DESCRIPTION
**Pull request by Dridi**
Only tested on Fedora 27.

### CODE REVIEW

**Comment by SimonKagstrom** [comment]
Merging, thanks!

The travis errors seems very unrelated to this. The clang build errors have been fixed in the system-mode-ng branch, so will be fixed when that is merged.

**Comment by Dridi** [comment]
Speaking of the test suite, I'm having trouble "just" running it. I submitted a review request [1] to include `kcov` in Fedora, but for now the packaging doesn't run the test suite. We have offline build requirements and as such I can't use `travis/Makefile`. Should I open an issue regarding an offline-able test suite?

[1] https://bugzilla.redhat.com/show_bug.cgi?id=kcov

**Comment by SimonKagstrom** [comment]
Nice to hear, thanks! I'm a fedora user myself (but a bit behind on versions).

As for the tests, it's not extremely complicated: The testsuite has an own cmake file (tests/CMakeLists.txt) which builds the binaries. The testsuite itself is then run with ```tests/tools/run-tests```, which also has some help:

```
$ tests/tools/run-tests
Usage: run-tests <path-to-kcov-binary> <kcov-output> <path-to-test-builds> <path-to-kcov-source>
```

So that should be pretty easy to use outside of travis. However, if I remember correctly, there are some tests which are x86-only, so running them on e.g., ARM would be problematic.


I also need to merge ```system-mode-ng``` before releasing the next version. The system-mode-ng branch is mainly lacking tests for now, and cleanup of the commits. There is also a regression, #212, which should be fixed before release.

**Comment by Dridi** [comment]
Indeed, if I build kcov in `build/` and the test suite in `build-tests/` I get this:

```
$ ../tests/tools/run-tests ../build/src/kcov output . ..
x....Clang-only
u.....x....u....u............xx..xx.......................x.......u....
----------------------------------------------------------------------
Ran 76 tests in 66.304s

OK (expected failures=7, unexpected successes=4)
```

As you can see [1] I already exclude most of the available architectures, so currently it's only x86 and ppc64 (big endian). Having the ability to skip tests on specific architectures should maybe be baked in the test suite, but I can do that for the whole test suite in the RPM spec too. I will have a closer look when I have time, because if it's shell I should be able to wrap my head around it.

I'm also curious about those unexpected successes :)

[1] https://dridi.fedorapeople.org/review/kcov.spec

**Comment by SimonKagstrom** [comment]
Even better, the test suite is written in Python :-)

Anyway, I think its more of a build issue. The test suite already contains checks for OS (OSX or Linux), so I think adding architectures shouldn't bee too hard.

There are unfortunately some test cases which are a bit unstable due to timing. As for the unexpected successes, I'll take a look at that again.

**Comment by SimonKagstrom** [comment]
In travis, there should now only be one unexpected successes (well, in system-mode-ng anyway), and that one is really unexpected. Or rather, the test case is slightly too limited for the bugs to really show.

**Comment by Dridi** [comment]
> Even better, the test suite is written in Python :-)

Too bad, I'm rather of the shell persuasion... I think I will wait for kcov-34 to start fiddling with the test suite.

**Pull request merged**
