### PR TITLE
add Dockerfile

### LINKED ISSUE #273: docker images are stale
The latest version on https://hub.docker.com/r/ragnaroek/kcov/ is stale, only has v33 as latest. I've gone ahead and registered the kcov org on docker hub since imo it seems nicer to either pull from a more official looking org/image (kcov/kcov) or from same layout as github (SimonKagstrom/kcov).

I'd like to fixup the sync to hub too, either continuing on with docker automatic builds or pushing from travis. I'm not sure which is preferable. But imo docker build source should be in this repo (similar to `debian` folder). Either way I'd like to set it up so docker tags are matched to git tags and docker image's `latest` tag corresponds to `master` branch.

### PR DESCRIPTION
**Pull request by mmlb**
fixes #273

### CODE REVIEW

**Comment by mmlb** [comment]
@SimonKagstrom I'll add you to the org as an admin (docker hub id?) and then you can point the kcov automated build over at this repo and it'll set up the github hooks.

**Comment by mmlb** [comment]
You can see/use the current builds here https://hub.docker.com/r/mmlb/kcov/

**Comment by mmlb** [comment]
Also, I just learned that I'll be able to trigger builds for older tags using curl, so we can have same tags as found on https://hub.docker.com/r/ragnaroek/kcov/tags/, namely v31-v33.

**Comment by SimonKagstrom** [comment]
@mmlb I'm SimonK on docker hub, although I've hardly used it so far.

Thanks for the changes!

**Comment by SimonKagstrom** [comment]
Hmm... I hope I managed to create it. I think I might have managed to create one on my own user as well by mistake.

It now gets stuck when I press create, but let's see how it turns out.

**Comment by mmlb** [comment]
I don't see anything yet, iirc it took a few minutes for hub to create the repo correctly. Also you may need to refresh perms or something so that docker hub picks up that you're part of the kcov org, did you see that as an option when creating the automated build?

**Comment by SimonKagstrom** [comment]
Ok, I realised my mistake. It's not SimonK, but simonkagstrom which is the user. Sorry about that! That explains why I wasn't in the organization I guess, although SimonK is also welcome :-)

**Comment by mmlb** [comment]
done, try again now?

**Comment by SimonKagstrom** [comment]
I think it has been created now, thanks!

**Comment by mmlb** [comment]
nice! I've added triggers for tags, manually triggered a build of master and will soon push the same v31-v33 images as was on the previous repo. I can also build v34-v36 using same Dockerfile and push them up.

**Comment by mmlb** [comment]
Just pushed up the v31-v33 images:
```
❯ docker images | grep kcov | sort -k 3
kcov/kcov                        v33                            5771c83b3b0d        21 months ago       520MB
ragnaroek/kcov                   v33                            5771c83b3b0d        21 months ago       520MB
kcov/kcov                        v31                            796274bf3329        2 years ago         530MB
ragnaroek/kcov                   v31                            796274bf3329        2 years ago         530MB
kcov/kcov                        v32                            f34f09d5663e        21 months ago       519MB
ragnaroek/kcov                   v32                            f34f09d5663e        21 months ago       519MB```

**Comment by mmlb** [comment]
v34 and v35 were generated with tweaked Dockerfile, v36 was unchanged:
```diff
--- ../Dockerfile       2018-10-24 16:52:08.898668548 -0400
+++ Dockerfile  2018-10-24 16:56:06.398770774 -0400
@@ -51,6 +51,5 @@
 COPY --from=builder /lib/x86_64-linux-gnu/*.so* /lib/x86_64-linux-gnu/
 COPY --from=builder /usr/lib/x86_64-linux-gnu/*.so* /usr/lib/x86_64-linux-gnu/
 COPY --from=builder /usr/local/bin/kcov* /usr/local/bin/
-COPY --from=builder /usr/local/share/doc/kcov /usr/local/chare/doc/kcov

 CMD ["/usr/local/bin/kcov"]

kcov /
```

**Comment by williamdes** [comment]
> You can see/use the current builds here https://hub.docker.com/r/mmlb/kcov/

This image seems to not be maintained since 6 years, maybe delete or update it ?

I did open a PR at https://github.com/shellspec/kcov-docker/pull/1 to have this other image updated

**Comment by SimonKagstrom** [comment]
@williamdes the "official" docker images are at **https://hub.docker.com/r/kcov/kcov**, which are update on releases (and also on each commit).

Anyway, thanks for keeping the shellspec/kcov-docker up-to-date!

**Comment by williamdes** [comment]
> @williamdes the "official" docker images are at **https://hub.docker.com/r/kcov/kcov**, which are update on releases (and also on each commit).
> 
> Anyway, thanks for keeping the shellspec/kcov-docker up-to-date!

Thank you, I did not know
Would you accept a multi arch setup for the Docker image?
The Dockerfile seems outdated I might try to refresh it to bookworm

**Comment by SimonKagstrom** [comment]
Absolutely!

I should say that this was contributed by another guy, I still use docker quite infrequently, and am by no means an expert at it.

**Pull request merged**
