### PR TITLE
Fix some issues in the Bash engine

### PR DESCRIPTION
**Pull request by beatussum**
This pull request refers to [this issue](https://github.com/SimonKagstrom/kcov/issues/457) I reported some days ago.

It's not perfect but it should do the job in most of the cases.

I tried to respect your coding style. I hope I haven't made mistake and I'm waiting for review.

All tests passed.

### CODE REVIEW

**Comment by SimonKagstrom** [comment]
Thanks!

You had a great example in the issue, is it possible to add that to a small test case?


Bash parsing is fairly nasty. The python support is much more slim, and easier to follow, but bash requires quite a lot of special cases. I had hopes of writing a proper parser, but with these changes (and some other), it's probably good enough as it is!

And as for the coding style, I've started to change it in some files, so right now everything is in flux and your changes look good to me :-)

**Comment by beatussum** [comment]
I've dropped the commit which was supposed to fix coverage of multiline arrays. Indeed, it seems to be quiet difficult as `trap <arg> DEBUG` does not have the same behavior with the different syntaxes used to initialize an array:

```bash
trap 'echo ${LINENO}' DEBUG

declare -a array=( # <- this line
    a
    b
    c
)

declare array=(
    a
    b
    c
) # <- this line

declare array=(
    a
    b
    c
) # <- this line
```

**Comment by SimonKagstrom** [comment]
Merged, thanks a lot!

**Comment by williamdes** [comment]
Hello here

I applied https://github.com/SimonKagstrom/kcov/commit/a6ff5ac44524d1bc9c298ca14c10edd41ded1cea on the v43 
And I get this test error

So I tried applying most of this pull-request, but still it fails on this test.
On my workstation it works fine, but on Debian testing it does not. Why, I have no idea.

Can you help me ?

```
======================================================================
FAIL: runTest (test_bash.bash_subshell.runTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/debian/kcov/debian/output/source_dir/tests/tools/test_bash.py", line 353, in runTest
    self.assertEqual(2, cobertura.hitsPerLine(dom, "subshell.sh", 4))
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 2 != 0
----------------------------------------------------------------------

```

**Comment by SimonKagstrom** [comment]
@williamdes I wonder if that actually is an issue with the test. It might be  that a later version of Debian containing a newer bash might report the line differently. It's this piece of code:

```
#/bin/sh
eval "(echo Stuff in subshell
echo More stuff in subshell
      ) "
```

where the last line is expected to be marked as executed, which the older bashes did. Perhaps the newer versions instead report the first line?

**Pull request merged**
